### ISSUE TITLE
Updating dependencies

### ISSUE THREAD

**Issue by kit-johnson** [spenceralger/rcloader#14]
rcloader depends on a version of lodash that has a high severity security vulnerability. Here's what I get from `npm audit`:

```
  Package         lodash
  Patched in      >=4.17.19
  Dependency of   jshint-loader [dev]
  Path            jshint-loader > rcloader > lodash
  More info       https://npmjs.com/advisories/1523
```

I'm still quite new to npm and so I'm not sure the best way to go about fixing this. Do I need to update dependencies myself? I tried to do that. I thought it would be good to first see if it passes tests, before changing anything. So I went into my app `folder\node_modules\rcloader` and ran `npm test`. The response I get is:

```
npm test
> rcloader@0.1.2 test …\node_modules\rcloader
> mocha

npm ERR! Test failed.  See above for more details.
```

There is nothing 'above'. I'm a bit stuck now about how to get this up-to-date, and would be very grateful for any help.

**Comment by spalger** [comment]
Hey @oldmankit, the copy of rcloader that's installed in projects is pretty mimimal and doesn't include the dependencies to do things like run the tests. I'll get rcloader updated real quick

**Comment by spalger** [comment]
Oh, missed that rcloader was pinned to `0.1.2` by `jshint-loader`, which has since been deprecated and the repository is now archived, so there isn't any way to update it. You will need to migrate away from `jshint-loader` to fix that issue. Sorry about that!

**Comment by kit-johnson** [comment]
I'm really grateful for your reply as it explains a couple of things. Now I know why the test didn't work. And if I understand correctly, the logjam here is that even if `rcloader` updates its `lodash` dependency, because `jshint-loader` is an archived project then it will never get the updated version of `rcloader`.

As you can tell I'm very new to this. Do you see a problem with me just forking `jshint-loader` to unpin it's `rcloader` dependency?

**Comment by spalger** [comment]
I suspect there's a reason they have pinned to an exact version of rcloader, but it's worth a shot! You can install from a local clone to test though if you want to make it easier to unwind if it doesn't work.
